# Generated by Django 4.2.18 on 2025-02-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_cidade_estado_pessoas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
    ]
